[tox]
envlist = py310, py311, py312, lint, type-check

[testenv]
deps =
    pytest
    pytest-cov
    -r requirements.txt
commands =
    pytest tests/ {posargs}

[testenv:lint]
deps =
    flake8
    black
    isort
commands =
    flake8 .
    black --check .
    isort --check .

[testenv:type-check]
deps =
    mypy
    -r requirements.txt
commands =
    mypy scripts/ utils/

[testenv:format]
deps =
    black
    isort
commands =
    black .
    isort .

[testenv:clean]
deps =
    coverage
skip_install = true
commands =
    coverage erase
    rm -rf dist
    rm -rf build
    rm -rf *.egg-info
    rm -rf .tox
    rm -rf .pytest_cache
    rm -rf .mypy_cache
    rm -rf __pycache__
    rm -rf */__pycache__
    rm -rf */*/__pycache__