name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}